language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0
  # - WP_VERSION=4.9 WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1

install:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install --no-dev
  - composer global require mockery/mockery
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then
      composer global require "phpunit/phpunit=5.6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

script:
  - phpunit
  - phpunit --config phpunit.integration.xml


after_success:
  - bash <(curl -s https://codecov.io/bash)
